# docker-compose build && docker-compose up
ckan:
  container_name: ckan
  image: ckan/ckan:latest
  links:
      - db
      - solr
      - redis
  ports:
      - "80:5000"

db:
  container_name: db
  image: ckan/postgresql:latest
  ports:
    - "5432:5432"
  
solr:
  container_name: solr
  image: ckan/solr:latest
  ports: 
    - "8983:8983"
    
redis:
  container_name: redis
  image: redis:latest
  ports: 
    - "6379:6379"
